name: Build App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v cron.go

    - name: Vet
      run: go vet .

    - name: Lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.3"
